/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libro;

import conexion.BaseDeDatos;
import conexion.IngresoElementos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import principal.InicioGestion;

/**
 *
 * @author Martinez
 */
public class GestionLibro extends javax.swing.JInternalFrame {
    DefaultTableModel modeloTabla;
    BaseDeDatos bd = new BaseDeDatos();
    public GestionLibro()
    {
        inicioTabla();
        initComponents();
        //setFilas();
    }
    
    public DefaultTableModel getDefaultTable()
    {
        return modeloTabla;
    }
    
    private void inicioTabla()
    {
        try
        {
            IngresoElementos ingE = new IngresoElementos();
            modeloTabla = new DefaultTableModel(null,getColumnas())
            {
                public boolean isCellEditable(int rowIndex,int columnIndex){return false;}
            };
            String sql = "select libro.serie,libro.isbn,libro.titulo,libro.paginas,libro.precio,libro.año,"
                    + "categoria_libro.categoria_cod_cate,autor_libro.autor_cod_autor, "
                    + "editorial.nombre,idioma_libro.idioma_cod_idioma,estado.descripcion from libro "
                    + "join categoria_libro on libro.serie=categoria_libro.libro_serie "
                    + "join autor_libro on libro.serie=autor_libro.libro_serie "
                    + "join idioma_libro on libro.serie=idioma_libro.libro_serie "
                    + "join editorial on editorial.cod_edi=libro.editorial_cod_edi "
                    + "join estado on estado.cod_estado=libro.estado_cod_estado";
            ingE.llenadoTabla(sql, modeloTabla);
        }
        catch(NullPointerException ex)
        {
            System.out.println("Error null: " +ex.getMessage());
        }
    }
    
    private String[] getColumnas()
    {
        String columnas[] = new String[]{"Serie","ISBN","Titulo","Paginas","Precio","Año","Categoria","Autor","Editorial","Idioma","Estado"};
        return columnas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rbtnAutor = new javax.swing.JRadioButton();
        rbtnEditorial = new javax.swing.JRadioButton();
        rbtnCategoria = new javax.swing.JRadioButton();
        rbtnIdioma = new javax.swing.JRadioButton();
        rbtnEstado = new javax.swing.JRadioButton();
        rbtnISBN = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        rbtnTitulo = new javax.swing.JRadioButton();
        rbtnSerie = new javax.swing.JRadioButton();
        btnLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Libro");

        tabla.setModel(modeloTabla);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Buscar por:");

        buttonGroup1.add(rbtnAutor);
        rbtnAutor.setText("Autor");
        rbtnAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnAutorMousePressed(evt);
            }
        });

        buttonGroup1.add(rbtnEditorial);
        rbtnEditorial.setText("Editorial");
        rbtnEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnEditorialMousePressed(evt);
            }
        });

        buttonGroup1.add(rbtnCategoria);
        rbtnCategoria.setText("categoria");
        rbtnCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnCategoriaMousePressed(evt);
            }
        });

        buttonGroup1.add(rbtnIdioma);
        rbtnIdioma.setText("Idioma");
        rbtnIdioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnIdiomaMousePressed(evt);
            }
        });
        rbtnIdioma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnIdiomaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnEstado);
        rbtnEstado.setText("Estado");
        rbtnEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnEstadoMousePressed(evt);
            }
        });

        buttonGroup1.add(rbtnISBN);
        rbtnISBN.setText("ISBN");
        rbtnISBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnISBNMousePressed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Buscar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTitulo);
        rbtnTitulo.setText("Titulo libro");
        rbtnTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnTituloMousePressed(evt);
            }
        });
        rbtnTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTituloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnSerie);
        rbtnSerie.setText("Serie libro");
        rbtnSerie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnSerieMousePressed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Autor");

        jMenuItem1.setText("Gestion Autor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editorial");

        jMenuItem2.setText("Gestion Editorial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Categoria");

        jMenuItem3.setText("Gestion Categoria");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Idioma");

        jMenuItem4.setText("Gestion Idioma");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Estado");

        jMenuItem5.setText("Gestion Estado");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtBuscar))
                        .addComponent(jSeparator6)
                        .addComponent(jSeparator5)
                        .addComponent(jSeparator4)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimpiar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtnCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnISBN, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rbtnEstado)
                                    .addComponent(rbtnAutor)
                                    .addComponent(rbtnIdioma))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnSerie)
                                    .addComponent(rbtnTitulo)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnIdioma)
                    .addComponent(rbtnISBN)
                    .addComponent(rbtnTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnEditorial)
                    .addComponent(rbtnEstado)
                    .addComponent(rbtnSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnCategoria)
                    .addComponent(rbtnAutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTituloActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GestionAutor gesAu = new GestionAutor();
        InicioGestion.jdVentana.add(gesAu);
        gesAu.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GestionEditorial gesEd = new GestionEditorial();
        InicioGestion.jdVentana.add(gesEd);
        gesEd.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GestionCategoria gesCat = new GestionCategoria();
        InicioGestion.jdVentana.add(gesCat);
        gesCat.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        GestionIdioma gesId = new GestionIdioma();
        InicioGestion.jdVentana.add(gesId);
        gesId.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        GestionEstado gesEs = new GestionEstado();
        InicioGestion.jdVentana.add(gesEs);
        gesEs.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        IngresoElementos ingE = new IngresoElementos();
        String busq = "", sql = "", opBusq;
        opBusq = txtBuscar.getText();
        ingE.limpiarTabla(tabla, modeloTabla); 
        if(rbtnAutor.isSelected() || rbtnCategoria.isSelected() || rbtnEditorial.isSelected()
                || rbtnEstado.isSelected() || rbtnISBN.isSelected() || rbtnIdioma.isSelected()
                || rbtnSerie.isSelected() || rbtnTitulo.isSelected())
        {
            if(rbtnAutor.isSelected())
            {
                busq = "autor_libro.autor_cod_autor";
            }
            if(rbtnCategoria.isSelected())
            {
                busq = "categoria_libro.categoria_cod_cate";
            }
            if(rbtnEditorial.isSelected())
            {
                busq = "editorial.nombre";
            }
            if(rbtnEstado.isSelected())
            {
                busq = "estado.descripcion";
            }
            if(rbtnISBN.isSelected())
            {
                busq = "libro.isbn";
            }
            if(rbtnIdioma.isSelected())
            {
                 busq = "idioma_libro.idioma_cod_idioma";
            }
            if(rbtnSerie.isSelected())
            {
                busq = "libro.serie";
            }
            if(rbtnTitulo.isSelected())
            {
                busq = "libro.titulo";
            }
            sql = "select libro.serie,libro.isbn,libro.titulo,libro.paginas,libro.precio,libro.año,"
                    + "categoria_libro.categoria_cod_cate,autor_libro.autor_cod_autor, "
                    + "editorial.nombre,idioma_libro.idioma_cod_idioma,estado.descripcion from libro "
                    + "join categoria_libro on libro.serie=categoria_libro.libro_serie "
                    + "join autor_libro on libro.serie=autor_libro.libro_serie "
                    + "join idioma_libro on libro.serie=idioma_libro.libro_serie "
                    + "join editorial on editorial.cod_edi=libro.editorial_cod_edi "
                    + "join estado on estado.cod_estado=libro.estado_cod_estado "
                    + "where "+ busq +" like '%"+ opBusq +"%'";
            ingE.llenadoTabla(sql, modeloTabla);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Seleccione una opcion a buscar","Advertencia",JOptionPane.WARNING_MESSAGE);
            sql = "select libro.serie,libro.isbn,libro.titulo,libro.paginas,libro.precio,libro.año,"
                    + "categoria_libro.categoria_cod_cate,autor_libro.autor_cod_autor, "
                    + "editorial.nombre,idioma_libro.idioma_cod_idioma,estado.descripcion from libro "
                    + "join categoria_libro on libro.serie=categoria_libro.libro_serie "
                    + "join autor_libro on libro.serie=autor_libro.libro_serie "
                    + "join idioma_libro on libro.serie=idioma_libro.libro_serie "
                    + "join editorial on editorial.cod_edi=libro.editorial_cod_edi "
                    + "join estado on estado.cod_estado=libro.estado_cod_estado";
            ingE.llenadoTabla(sql, modeloTabla);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        IngresoElementos ingE = new IngresoElementos();
        String sql = "select libro.serie,libro.isbn,libro.titulo,libro.paginas,libro.precio,libro.año,"
                    + "categoria_libro.categoria_cod_cate,autor_libro.autor_cod_autor, "
                    + "editorial.nombre,idioma_libro.idioma_cod_idioma,estado.descripcion from libro "
                    + "join categoria_libro on libro.serie=categoria_libro.libro_serie "
                    + "join autor_libro on libro.serie=autor_libro.libro_serie "
                    + "join idioma_libro on libro.serie=idioma_libro.libro_serie "
                    + "join editorial on editorial.cod_edi=libro.editorial_cod_edi "
                    + "join estado on estado.cod_estado=libro.estado_cod_estado";
        buttonGroup1.clearSelection();
        txtBuscar.setText("");
        ingE.limpiarTabla(tabla, modeloTabla);
        ingE.llenadoTabla(sql, modeloTabla);  
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarLibro agLib = new AgregarLibro();
        agLib.desbloquearInterfaz();
        agLib.ingresoSerie();
        InicioGestion.jdVentana.add(agLib);
        agLib.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        AgregarLibro agLib = new AgregarLibro();
        InicioGestion.jdVentana.add(agLib);
        agLib.edicionElementoTabla();
        agLib.show();
        agLib.agregarFrame(tabla,modeloTabla);
    }//GEN-LAST:event_tablaMouseClicked

    private void rbtnIdiomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnIdiomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnIdiomaActionPerformed

    private void rbtnISBNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnISBNMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnISBNMousePressed

    private void rbtnIdiomaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnIdiomaMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnIdiomaMousePressed

    private void rbtnTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnTituloMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnTituloMousePressed

    private void rbtnEditorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnEditorialMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnEditorialMousePressed

    private void rbtnEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnEstadoMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnEstadoMousePressed

    private void rbtnSerieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnSerieMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnSerieMousePressed

    private void rbtnCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnCategoriaMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnCategoriaMousePressed

    private void rbtnAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAutorMousePressed
        txtBuscar.setText("");
    }//GEN-LAST:event_rbtnAutorMousePressed

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        if(rbtnAutor.isSelected() || rbtnCategoria.isSelected() || rbtnEditorial.isSelected()
                || rbtnEstado.isSelected() || rbtnISBN.isSelected() || rbtnIdioma.isSelected()
                || rbtnSerie.isSelected() || rbtnTitulo.isSelected())
        {
            if(rbtnTitulo.isSelected() || rbtnEditorial.isSelected() || rbtnEstado.isSelected())
            {
                IngresoElementos ingE = new IngresoElementos();
                ingE.limiteCaracteres(evt, txtBuscar, 29);
            }
            else
            {
                IngresoElementos ingE = new IngresoElementos();
                ingE.soloNumeros(evt, txtBuscar);
            }
        } 
    }//GEN-LAST:event_txtBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton rbtnAutor;
    private javax.swing.JRadioButton rbtnCategoria;
    private javax.swing.JRadioButton rbtnEditorial;
    private javax.swing.JRadioButton rbtnEstado;
    private javax.swing.JRadioButton rbtnISBN;
    private javax.swing.JRadioButton rbtnIdioma;
    private javax.swing.JRadioButton rbtnSerie;
    private javax.swing.JRadioButton rbtnTitulo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
